// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtahMotorVehicleAccidentAnalysis.Models;

namespace UtahMotorVehicleAccidentAnalysis.Migrations.AccidentsDb
{
    [DbContext(typeof(AccidentsDbContext))]
    partial class AccidentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UtahMotorVehicleAccidentAnalysis.Models.Accident", b =>
                {
                    b.Property<int>("CRASH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("BICYCLIST_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CITY")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("COMMERCIAL_MOTOR_VEH_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("COUNTY_NAME")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CRASH_DATETIME")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CRASH_SEVERITY_ID")
                        .HasColumnType("int");

                    b.Property<bool>("DISTRACTED_DRIVING")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DOMESTIC_ANIMAL_RELATED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DROWSY_DRIVING")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DUI")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IMPROPER_RESTRAINT")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("INTERSECTION_RELATED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LAT_UTM_Y")
                        .HasColumnType("int");

                    b.Property<int>("LONG_UTM_X")
                        .HasColumnType("int");

                    b.Property<string>("MAIN_ROAD_NAME")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MILEPOINT")
                        .HasColumnType("int");

                    b.Property<bool>("MOTORCYCLE_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NIGHT_DARK_CONDITION")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OLDER_DRIVER_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OVERTURN_ROLLOVER")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PEDESTRIAN_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ROADWAY_DEPARTURE")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ROUTE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("SINGLE_VEHICLE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TEENAGE_DRIVER_INVOLVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UNRESTRAINED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WILD_ANIMAL_RELATED")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WORK_ZONE_RELATED")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CRASH_ID");

                    b.ToTable("Accidents");
                });
#pragma warning restore 612, 618
        }
    }
}
